openapi: 3.0.0
info:
  title: Mercury backend API
  version: 1.0.0
  description: This is an API application made with Express and documented with Swagger

paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              example:
                status: "ok"
                users:
                  - nick: "boejiden"
                    country: "USA"
                    password: "sleepyjoe"
                    mail: "joe.biden@gmail.com"
                    friend_ids:
                      - 2
                    chats: []
                    last_name: "Biden"
                    profile_picture: "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ea/ec/36/eaec3686-c87d-1957-8d44-c6b8addda35a/pr_source.png/256x256bb.jpg"
                    first_name: "Joe"
                  - nick: "adamos"
                    country: "Poland"
                    password: "mysz888"
                    mail: "adammalysz123@wp.pl"
                    friend_ids: []
                    chats: []
                    last_name: "Ma≈Çysz"
                    profile_picture: "https://www.wingsforlifeworldrun.com/uploads/fit/256/256/users/9qGOWl/avatar.1618305209.jpg"
                    first_name: "Adam"
    post:
      summary: Create a new User
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
              
      responses:
        '200':
          description: The created User
          content:
            application/json:
              example:
                status: "ok"
                user:
                  - nick: "Tommy"
                    country: "USA"
                    password: "12345"
                    mail: "tom.hanks@example.com"
                    friend_ids:
                      - 2
                    chats: []
                    last_name: "Hanks"
                    profile_picture: "https://example.com/tommy.jpg"
                    id: "9e35681f-091e-461b-bbb9-75e0cbadb013"
                    first_name: "Tom"


components:
  schemas:
    User:
      type: object
      required:
        - nick
        - password
        - first_name
        - last_name
        - country
        - profile_picture
        - mail
      properties:
        nick:
          type: string
          description: The nick of the user
        password:
          type: string
          description: The password of the user
        first_name:
          type: string
          description: The first name of the user
        last_name:
          type: string
          description: The last name of the user
        country:
          type: string
          description: The country of the user  
        profile_picture:
          type: string
          description: The profile picture link of the user
        mail:
          type: string
          description: The e-mail of the user
        friend_ids:
          type: array
          description: The array of friends of the user
        chats:
          type: array
          description: The array of chats of the user
  
  requestBodies:
    UserBody:
      description: A JSON object containing User information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
          example:
            nick: "Tommy"
            country: "USA"
            password: "12345"
            mail: "tom.hanks@example.com"
            first_name: "Tom"
            last_name: "Hanks"
            profile_picture: "https://example.com/tommy.jpg"
